### ISSUE TITLE
why discord rpc

### ISSUE THREAD

**Issue by oasn** [ajisswag/Samarium#3]
Traceback (most recent call last):
  File "Samarium_GUI.py", line 144, in <module>
  File "pypresence\presence.py", line 13, in __init__
  File "pypresence\baseclient.py", line 28, in __init__
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.

why even putting a RPC to that?

**Comment by ajisswag** [comment]
It says in the module pypresence, thats for the Discord RPC, it's not a logger.
